---
title: "Sumi focus perception results"
output: html_document
---

## 1. Load Data
```{r}
library(Rmisc)
library(ggplot2)
library(dplyr)

#rm(list=ls())
SumiFoc.df <- read.csv("data/results.csv", header = TRUE, sep = ",")

# Convert from wide to long format
#library(tidyr)
#SumiFoc.long <- gather(SumiFoc.df, key = "Listener", value = "Score", L01:L12)
#View(SumiFoc.wide)
#SumiFoc.long$Listener <- as.factor(SumiFoc.long$Listener)
#str(SumiFoc.long)

SumiFoc.df$predicate_gloss <- factor(SumiFoc.df$predicate_gloss, levels = c("chasing", "sleeping", "bigger"))
SumiFoc.df$factor <- paste(SumiFoc.df$predicate_gloss, SumiFoc.df$condition, sep = "_")
SumiFoc.df$factor <- factor(SumiFoc.df$factor, levels = c("chasing_broad","sleeping_broad","chasing_narrow","sleeping_narrow","bigger_narrow"))
SumiFoc.df$score <- SumiFoc.df$key_resp_5.keys
SumiFoc.df$score <- gsub("w", 1, SumiFoc.df$score)
SumiFoc.df$score <- gsub("f", 2, SumiFoc.df$score)
SumiFoc.df$score <- gsub("j", 3, SumiFoc.df$score)
SumiFoc.df$score <- gsub("p", 4, SumiFoc.df$score)
SumiFoc.df$score <- as.integer(SumiFoc.df$score)

# Group all tone tokens into tone types
SumiFoc.df$AS_tone <- gsub(".{1}$", "", SumiFoc.df$AS_tone)

# Omit participant 0
SumiFoc.df <- subset(SumiFoc.df, participant != "0")
#SumiFoc.df <- subset(SumiFoc.df, participant == "0")

# Omit participant 9
#SumiFoc.df <- subset(SumiFoc.df, participant != "5")
SumiFoc.df <- subset(SumiFoc.df, participant != "9")
```


## 2. Look at effect of Condition (Carrier1 vs. Isol1 vs. Isol3) on Score
```{r}
# Count number of each rating, by factor
count(SumiFoc.df, factor, score)

# Summarize by and Condition & Listener
SumiFoc.summ <- summarySE(SumiFoc.df, "score", groupvars = c("predicate_gloss", "condition"), na.rm = TRUE)
SumiFoc.summ
SumiFoc.summ$factor <- paste(SumiFoc.summ$predicate_gloss, SumiFoc.summ$condition, sep = "_")
SumiFoc.summ$factor <- factor(SumiFoc.summ$factor, levels = c("chasing_broad","sleeping_broad","chasing_narrow","sleeping_narrow","bigger_narrow"))
#SumiFoc.summ$factor <- interaction(SumiFoc.summ$predicate_gloss, SumiFoc.summ$condition)

# Boxplot
SumiFoc.boxplot <- ggplot(SumiFoc.df, aes(x=factor, y=score)) + 
  geom_boxplot(aes(fill = predicate_gloss)) +
  scale_fill_brewer(palette = "YlGnBu") +
  theme_bw() +
  labs(x = "Sentence type & Focus condition", y = "Rating\n1 = Narrow Focus, 4 = Broad Focus") +
  scale_x_discrete(limits = rev(levels(SumiFoc.df$factor)), labels = c("verbless\nnarrow","intransitive\nnarrow","transitive\nnarrow","intransitive\nbroad","transitive\nbroad")) +
  theme(axis.title = element_text(size = 17.5),
        axis.text = element_text(size = 16)) + #Adjust font size of axes
  theme(legend.position="none") +
  coord_flip()
SumiFoc.boxplot

#Save as PNG file
png(file = "figures/SumiFoc-perception_score-8subjects-box.png", width = 500, height = 450, res = 72)
SumiFoc.boxplot
dev.off()

SumiFoc.violinplot <- ggplot(SumiFoc.df, aes(x=factor, y=score)) + 
  geom_violin(aes(fill = predicate_gloss)) +
  stat_summary(fun.y = median, geom = "point", size = 2, color = "black") +
  scale_fill_brewer(palette = "YlGnBu") +
  theme_bw() +
  labs(x = "Sentence type & Focus condition", y = "Rating\n1 = Narrow Focus, 4 = Broad Focus") +
  scale_x_discrete(limits = rev(levels(SumiFoc.df$factor)), labels = c("verbless\nnarrow","intransitive\nnarrow","transitive\nnarrow","intransitive\nbroad","transitive\nbroad")) +
  theme(axis.title = element_text(size = 17.5),
        axis.text = element_text(size = 16)) + #Adjust font size of axes
  theme(legend.position="none") +
  coord_flip()
SumiFoc.violinplot

#Save as PNG file
png(file = "figures/SumiFoc-perception_score-8subjects-violin.png", width = 715, height = 645, res = 72)
SumiFoc.violinplot
dev.off()

#SumiFoc.subset <- subset(SumiFoc.df, predicate_gloss != "bigger")
#boxplot(score ~ AS_tone, data = SumiFoc.subset, main = "Score by Tone", ylab = "Tone", xlab = "1 = Narrow Focus, 4 = Broad Focus", ylim=c(0,5), horizontal = T)
```

## Save RData
```{r}
save.image(file="output/SumiFoc-perception.RData")
```